### ISSUE TITLE
code for how to construct the dataset from multi-view geometry ?

### ISSUE THREAD

**Issue by vicentowang** [wholebody3d/wholebody3d#10]
i wanna to build a dataset with all video sequences.

**Comment by Zhuyue0324** [comment]
I am very sorry that I had problem of accessing Github during my holiday in July so I can only answer your question now after I return back to work.

Our paper has been accepted to ICCV 2023 recently, and we claimed in the supplementary material that 'We will make the H3WB annotations and source code publicly available upon acceptance of the paper'. So yes, we will release the code you want after we clean it up and upload it, in no more than 2 weeks (deadline of ICCV camera ready version). You will be notified once they are uploaded.
