### ISSUE TITLE
question about 3d  coordinate system？

### ISSUE THREAD

**Issue by timegoby** [wholebody3d/wholebody3d#11]
I have read https://github.com/wholebody3d/wholebody3d/issues/5#issuecomment-1367410289, 
but I don't understand why the math formula between camera coordinates or world coordinates shown above，is there any introduction  about that for I'm readly new in this area.
Thanks a lot.

**Comment by Zhuyue0324** [comment]
Do you mean you don't understand X_cam = R_cam * X_global + T_cam?

**Comment by timegoby** [comment]
yes

**Comment by Zhuyue0324** [comment]
https://en.wikipedia.org/wiki/Camera_resectioning:
Extrinsic parameters
R , T R,T are the extrinsic parameters which denote the coordinate system transformations from 3D world coordinates to 3D camera coordinates. Equivalently, the extrinsic parameters define the position of the [camera center](https://en.wikipedia.org/wiki/Camera_center) and the camera's heading in world coordinates.

And no, 3d position recorded in the dataset is neither camera coordinates nor world coordinates as for now. It is X_dataset = R_cam * X_global
To obtain camera coordinates, you need X_cam = X_data + T_cam

**Comment by timegoby** [comment]
Thanks, I get it.
And how can I get the T_cam for each 3d positon sample? Is the follow steps right?
1. get sample_id of each 3d positon sample in 2Dto3D_train.json
2. get img_path in RGBto3D_train.json by match the sample_id above
3. assume the img_path is 'S5/Images/Directions 1.60457274/frame_2190.jpg'，then I can get the T_cam by match S5 and 60457274 below (the camera extrinsic data is acquire in VideoPose3d)

'S5': {
        '54138969': {
            'orientation': [0.1467377245426178, -0.162370964884758, -0.7551892995834351, 0.6178938746452332],
            'translation': [2097.3916015625, 4880.94482421875, 1605.732421875],
        },
        '55011271': {
            'orientation': [0.6159758567810059, -0.7626792192459106, -0.15728192031383514, 0.1189815029501915],
            'translation': [2031.7008056640625, -5167.93310546875, 1612.923095703125],
        },
        '58860488': {
            'orientation': [0.14291371405124664, -0.12907841801643372, 0.7678384780883789, -0.6110143065452576],
            'translation': [-1620.5948486328125, 5171.65869140625, 1496.43701171875],
        },
        '60457274': {
            'orientation': [0.5920479893684387, -0.7814217805862427, 0.1274748593568802, -0.15036417543888092],
            'translation': [-1637.1737060546875, -3867.3173828125, 1547.033203125],
        },
    }

**Comment by Zhuyue0324** [comment]
Yes, you are correct

**Comment by timegoby** [comment]
OK, thanks a lot !  Have a nice day ~

**Comment by timegoby** [comment]
```
import pd
```

**Comment by Zhuyue0324** [comment]
有两个地方你需要注意
第一, 你可以在datasets/data_preparation.py 找到我们是如何提取对应图片的. (实际上我们只每5帧使用一张图, each_x_frame=5, 来模拟训练数据的提取间隔, 你可以发现我们所以使用照片id都是5的倍数). 你可以确认一下用他们的方法和我们的代码提取出来的对应你两个pose的图片是不是同一张
第二, 还是之前坐标系的原因. h36m用的是相机坐标系,而我们不是, 是R_相机 * X_全局, 当然坐标不一样. 我们的坐标还要加上T_相机才是相机坐标系

**Comment by timegoby** [comment]
最后我发现是找的 T_相机 数据有问题：
第一，有些训练数据的间隔不是固定的5帧，而是5的倍数，比如 S1-Directions 的frame_ids是：
```
5, 10, 15, 20, 25, 30, 35, 45, 60, 65, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 145, 150, 175, 190, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 335, 345, 350, 355, 360, 365, 380, 385, 390, 410, 415, 420, 425, 430, 435, 445, 455, 465, 470, 480, 485, 490, 495, 500, 505, 510, 515, 585, 590, 595, 600, 605, 655, 690, 700, 705, 715, 720, 725, 730, 735, 740, 745, 750, 755, 770, 795, 800, 805, 810, 815, 820, 825, 835, 845, 855, 860, 865, 870, 875, 885, 890, 895, 900, 905, 910, 915, 920, 925, 930, 935, 940, 945, 950, 955, 970, 975, 980, 985, 995, 1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040, 1045, 1050, 1055, 1060, 1065, 1080, 1085, 1090, 1105, 1110, 1115, 1160, 1165, 1170, 1175, 1255, 1315, 1320, 1340, 1355, 1365, 1390, 1395, 1400, 1405, 1410, 1415, 1420, 1430, 1435, 1440, 1445, 1450, 1455, 1460, 1465, 1470, 1475, 1480, 1485, 1490, 1495, 1500, 1505, 1510, 1515, 1520, 1525, 1530, 1535, 1540, 1545, 1555, 1560, 1565, 1570, 1575, 1580, 1585, 1590, 1595, 1600, 1605, 1610]
```
第二，T_相机参数应该参考https://github.com/karfly/human36m-camera-parameters/blob/master/camera-parameters.json，而不是videoPose3d项目里面的
