### ISSUE TITLE
Facing Error with dimensions

### ISSUE THREAD

**Issue by Zinia17** [wholebody3d/wholebody3d#14]
hi, I have tried to use the following model of `SimpleBaseline`, but it is giving error.  

Error: 
`
torch.Size([16, 1, 266])
Traceback (most recent call last):
  File ".\wholebody3d\models\SimpleBaseline.py", line 174, in <module>
    avg_loss = train_one_epoch(epoch_number, 0,training_loader, model)
  File ".\wholebody3d\models\SimpleBaseline.py", line 56, in train_one_epoch
    outputs = model(inputs)
  File ".\wholebody3d\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".\wholebody3d\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File ".\wholebody3d\models\SimpleBaseline.py", line 27, in forward
    x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn1(self.fc1(x))))
  File ".\wholebody3d\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".\wholebody3d\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File ".\wholebody3d\venv\lib\site-packages\torch\nn\modules\batchnorm.py", line 171, in forward
    return F.batch_norm(
  File ".\wholebody3d\venv\lib\site-packages\torch\nn\functional.py", line 2478, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 1 elements not 1024

Process finished with exit code 1
`

Edited Code: 
`
  import os
  import torch
  import torch.nn as nn
  from torch.utils.data import Dataset, DataLoader
  
  from datetime import datetime
  from utils import json_loader_part, draw_skeleton
  
  
  class model_A_simple_yet_effective_baseline_for_3d_human_pose_estimation(nn.Module):
      def __init__(self):
          super(model_A_simple_yet_effective_baseline_for_3d_human_pose_estimation, self).__init__()
          self.upscale = nn.Linear(133*2, 1024)
          self.fc1 = nn.Linear(1024, 1024)
          self.bn1 = nn.BatchNorm1d(1024)
          self.fc2 = nn.Linear(1024, 1024)
          self.bn2 = nn.BatchNorm1d(1024)
          self.fc3 = nn.Linear(1024, 1024)
          self.bn3 = nn.BatchNorm1d(1024)
          self.fc4 = nn.Linear(1024, 1024)
          self.bn4 = nn.BatchNorm1d(1024)
          self.outputlayer = nn.Linear(1024, 133*3)
  
      def forward(self, x):
          x = self.upscale(x)
          x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn1(self.fc1(x))))
          x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn2(self.fc2(x1))))
          x = x + x1
          x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn3(self.fc3(x))))
          x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn4(self.fc4(x1))))
          x = x + x1
          x = self.outputlayer(x)
          return x
  
  
  
  def train_one_epoch(epoch_index, tb_writer, training_loader, model):
      running_loss = 0.
      last_loss = 0.
  
      for i, data in enumerate(training_loader):
          # Every data instance is an input + label pair
          inputs, labels = data
          # Zero your gradients for every batch!
          optimizer.zero_grad()
          # Make predictions for this batch
          outputs = model(inputs)
          # Compute the loss and its gradients
          loss = loss_fn(outputs, labels)
          loss.backward()
          # Adjust learning weights
          optimizer.step()
          # Gather data and report
          running_loss += loss.item()
          if i % 1000 == 999:
              last_loss = running_loss / 1000 # loss per batch
              print('  batch {} loss: {}'.format(i + 1, last_loss))
              tb_x = epoch_index * len(training_loader) + i + 1
              # tb_writer.add_scalar('Loss/train', last_loss, tb_x)
              running_loss = 0.
  
      return last_loss
  
  
  class CustomDataset(Dataset):
      def __init__(self, features, labels):
          self.features = features
          self.labels = labels
  
      def __len__(self):
          return len(self.features)
  
      def __getitem__(self, index):
          return self.features[index], self.labels[index]
  
  
  
  if __name__ == "__main__":
      device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
      model = model_A_simple_yet_effective_baseline_for_3d_human_pose_estimation().to(device)
  
      print("====================Simulation================")
      data_path= '.\wholebody3d\datasets\json'
      input_list_train, target_list_train = json_loader_part(data_path, 1)
      input_list_test, target_list_test = json_loader_part(data_path, 2)
  
      input_list_train = torch.cat(input_list_train, dim=0)
      input_list_train = torch.reshape(input_list_train, (input_list_train.shape[0], 1, -1))
  
      target_list_train = torch.cat(target_list_train, dim=0)
      target_list_train = torch.reshape(target_list_train, (target_list_train.shape[0], 1, -1))
  
      input_list_test = torch.cat(input_list_test, dim=0)
      input_list_test = torch.reshape(input_list_test, (input_list_test.shape[0], 1, -1))
  
      target_list_test = torch.cat(target_list_test, dim=0)
      target_list_test = torch.reshape(target_list_test, (target_list_test.shape[0], 1, -1))
  
      print("============Creating a DataLoader===========")
      train_dataset = CustomDataset(input_list_train, target_list_train)
      validation_dataset = CustomDataset(input_list_test, target_list_test)
  
      print("Create data loaders for our datasets; shuffle for training, not for validation")
      batch_size = 16
      training_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
      validation_loader = torch.utils.data.DataLoader(validation_dataset, batch_size=batch_size, shuffle=False)
  
  
      print("============ Selecting Loss function ===========")
      loss_fn = torch.nn.CrossEntropyLoss()
     
      print("============Selecting an Optimizer===========")  
      optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
  
  
      print("============Starting Epoch ===========")
      timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
      epoch_number = 0
  
      EPOCHS = 2
  
      best_vloss = 1_000_000.
  
      for epoch in range(EPOCHS):
          print('EPOCH {}:'.format(epoch_number + 1))       
          model.train(True)       
          avg_loss = train_one_epoch(epoch_number, 0,training_loader, model)
          running_vloss = 0.0
          
          model.eval()    
          with torch.no_grad():
              for i, vdata in enumerate(validation_loader):
                  vinputs, vlabels = vdata
                  voutputs = model(vinputs)
                  vloss = loss_fn(voutputs, vlabels)
                  running_vloss += vloss
  
          avg_vloss = running_vloss / (i + 1)
          print('LOSS train {} valid {}'.format(avg_loss, avg_vloss))
        
          # Track best performance, and save the model's state
          if avg_vloss < best_vloss:
              best_vloss = avg_vloss
              model_path = 'model_{}_{}'.format(timestamp, epoch_number)
              torch.save(model.state_dict(), model_path)
  
          epoch_number += 1

`

**Comment by Zhuyue0324** [comment]
If 0.001 is to high as learning rate then try 0.005, 0.002, 0.0001, etc.
You need to tune your parameter depending on your data and performance

**Comment by Zhuyue0324** [comment]
For your error of dimension, I remember the input dimension should be batchsize x 266, not batchize x1 x 266

**Comment by Zinia17** [comment]
Thank your for your kind response. sorry to bother you again. 
**now I am getting the following output: which showing very high error. where as train loss is always zero.** 
C:\PycharmProjects\wholebody3d\venv\Scripts\python.exe C:\PycharmProjects\wholebody3d\models\SimpleBaseline.py 
====================Simulation================
============Selecting an Optimizer===========
============Starting Epoch ===========
EPOCH 1: LOSS train 0.0 valid -82003072.0
EPOCH 2: LOSS train 0.0 valid -81999424.0
EPOCH 3: LOSS train 0.0 valid -82006936.0
EPOCH 4: LOSS train 0.0 valid -82004944.0
EPOCH 5: LOSS train 0.0 valid -82006040.0
Process finished with exit code 0



Code:
- I have used the models/SimpleBaseline.py file for performing task-1
- Loaded dataset from json that you have provided file using part-1 and validated using part-2

`
import os
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, TensorDataset

from datetime import datetime
from utils import json_loader_part, draw_skeleton


class model_A_simple_yet_effective_baseline_for_3d_human_pose_estimation(nn.Module):
    def __init__(self):
        super(model_A_simple_yet_effective_baseline_for_3d_human_pose_estimation, self).__init__()
        self.upscale = nn.Linear(133*2, 1024)
        self.fc1 = nn.Linear(1024, 1024)
        self.bn1 = nn.BatchNorm1d(1024)
        self.fc2 = nn.Linear(1024, 1024)
        self.bn2 = nn.BatchNorm1d(1024)
        self.fc3 = nn.Linear(1024, 1024)
        self.bn3 = nn.BatchNorm1d(1024)
        self.fc4 = nn.Linear(1024, 1024)
        self.bn4 = nn.BatchNorm1d(1024)
        self.outputlayer = nn.Linear(1024, 133*3)

    def forward(self, x):
        x = x.view(-1, 1 * 133 * 2) # added by zinia which is same as (-1, 266)
        x = self.upscale(x)
        x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn1(self.fc1(x))))
        x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn2(self.fc2(x1))))
        x = x + x1
        x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn3(self.fc3(x))))
        x1 = nn.Dropout(p=0.5)(nn.ReLU()(self.bn4(self.fc4(x1))))
        x = x + x1
        x = self.outputlayer(x)
        x = x.view(-1, 1 * 133 * 3) # added by zinia which is same as (-1, 399)
        return x



def train_one_epoch(epoch_index, tb_writer, training_loader, model):
    running_loss = 0.
    last_loss = 0.

    for i, data in enumerate(training_loader):
        # Every data instance is an input + label pair
        inputs, labels = data

        # Zero your gradients for every batch!
        optimizer.zero_grad()
        # Make predictions for this batch
        outputs = model(inputs)
        # Compute the loss and its gradients
        outputs = outputs.view(-1, 1, 133, 3)
        loss = loss_fn(outputs, labels)
        loss.backward()
        # Adjust learning weights
        optimizer.step()
        # Gather data and report
        running_loss += loss.item()
        if i % 1000 == 999:
            last_loss = running_loss / 1000 # loss per batch
            print('  batch {} loss: {}'.format(i + 1, last_loss))
            tb_x = epoch_index * len(training_loader) + i + 1
            running_loss = 0.

    return last_loss



if __name__ == "__main__":
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model_A_simple_yet_effective_baseline_for_3d_human_pose_estimation().to(device)

    print("====================Simulation================")
    data_path= 'C:\PycharmProjects\wholebody3d\datasets\json'
    input_list_train, target_list_train = json_loader_part(data_path, 1)
    input_list_test, target_list_test = json_loader_part(data_path, 2)

    input_list_train = torch.stack(input_list_train)
    target_list_train = torch.stack(target_list_train)
    input_list_test = torch.stack(input_list_test)
    target_list_test = torch.stack(target_list_test)

    train_dataset = TensorDataset(input_list_train, target_list_train)
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=False)

    val_dataset = TensorDataset(input_list_test, target_list_test)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)


    loss_fn = torch.nn.CrossEntropyLoss()

    print("============Selecting an Optimizer===========")
    # Optimizers specified in the torch.optim package, changing lr to 0.0001 from 0.001
    optimizer = torch.optim.SGD(model.parameters(), lr=0.0001, momentum=0.9)


    print("============Starting Epoch ===========")
    # per epoch activity
    # Initializing in a separate cell so we can easily add more epochs to the same run
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    # writer = SummaryWriter('runs/fashion_trainer_{}'.format(timestamp))
    epoch_number = 0
    EPOCHS = 5
    best_vloss = 1_000_000.

    for epoch in range(EPOCHS):
        print('EPOCH {}:'.format(epoch_number + 1))

        model.train(True)
        avg_loss = train_one_epoch(epoch_number, 0,train_loader, model)

        running_vloss = 0.0
        model.eval()

        with torch.no_grad():
            for i, vdata in enumerate(val_loader):
                vinputs, vlabels = vdata
                voutputs = model(vinputs)
                voutputs = voutputs.view(-1, 1* 133* 3)
                vlabels = vlabels.view(-1, 1* 133* 3)
                vloss = loss_fn(voutputs, vlabels)
                running_vloss += vloss

        avg_vloss = running_vloss / (i + 1)
        print('LOSS train {} valid {}'.format(avg_loss, avg_vloss))

        if avg_vloss < best_vloss:
            best_vloss = avg_vloss
            model_path = 'model_{}_{}'.format(timestamp, epoch_number)
            torch.save(model.state_dict(), model_path)

        epoch_number += 1
`

**Comment by davidpicard** [comment]
Are you using cross entropy to do regression?

**Comment by Zhuyue0324** [comment]
I have two suggestionss:
1. As sugguested by David, you don't use cross entropy loss when groundtruth are coordinates instead of 0-1 indicaters. You can just use L1 or L2 loss.
2. I remember SGD with momentum as optimizer is not stable when I ran before on my side, Adam is more common.

**Comment by Zinia17** [comment]
Thank you for your valuable suggestions.
