### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by anjugopinath** [wholebody3d/wholebody3d#15]
Do you have a script to perform 2D/3D pose estimation on images ?

**Comment by davidpicard** [comment]
Not yet, but it should be fairly easy to do: 
- Follow the OpenPifPaf tutorial to get wholebody predictions from the image
- Feed the predictions to one of our models that do incomplete 2D to 3D pose lifting to predict the 3D wholebody pose

Best, 
David.
