### ISSUE TITLE
How to train the modle

### ISSUE THREAD

**Issue by Z-mingyu** [wholebody3d/wholebody3d#18]
Your dataset is a very meaningful  dataset for 3D whole-body HPE, and I would like to use it in my research .

my question is how  to train the model . the  code in test_leaderboard.py is 
`   cross_validation = 0
    for i in range(6):
        if 'cv' + str(i) in data_path:
            cross_validation = i`

while 'cv' in the data_path, the  code will train the model . but  there isn't such file while contains the 'cv' in the file name  in the json.zip

We are looking forward to your answer.

**Comment by Zhuyue0324** [comment]
Generally, XXX_train.json are for training and XXX_test.json are for test. This is flagged as cross_validation=0 (no cross validation)

If you want to do cross validation for your self, just use XXX_train.json, which has 80k samples
Then using 0-15999 as test and rest as train is flagged as cross_validation=1
using 160000-31999 as test and rest as train is flagged as cross_validation=2
...
 using 64000-79999 as test and rest as train is flagged as cross_validation=5

When you use test_leaderboard.py, we assume you save the predicted coordinates on test set under the name format (task name)_pred[_cvX].json and send us the downloadable link so as we evaluate for you on groundtruth test set which is not given to you. But if you do cross validation (cv1-cv5), you have the groundtruth on your own in XXX_train.json, thus you can evaluate on your own and don't need us. Thus we remove the optional [_cvX] part (by default cv0) 

For details, please check the Tasks and Evaluation section in Readme.md

**Comment by Z-mingyu** [comment]
thanks for your reply.
