### ISSUE TITLE
NumPy data for test set

### ISSUE THREAD

**Issue by SoroushMehraban** [wholebody3d/wholebody3d#22]
Hello,
could you also please provide the numpy file for the test set (2D data)? I just want to make sure that if I use the training numpy file, then for the final test set, it has the exact same normalization (if applied anny).

**Comment by nerminsamet** [comment]
Hello, 
we have released the test sets. Please check [here](https://github.com/wholebody3d/wholebody3d?tab=readme-ov-file#updates).
