### ISSUE TITLE
data

### ISSUE THREAD

**Issue by herochen7372** [wholebody3d/wholebody3d#23]
![03aa2d357818a49a30d598e4745ac65](https://github.com/wholebody3d/wholebody3d/assets/97960617/7ad960eb-6662-47a9-9fb2-b6fba0542bb5)

Can you tell me how I can match the 3D coordinates in the json file with the image in human36M?

**Comment by Zhuyue0324** [comment]
We don't use this image path by default, but using our [data_preparation.py](https://github.com/wholebody3d/wholebody3d/blob/main/datasets/data_preparation.py) script to compile image from video.

However, you can check the closed issue #12 for how to convert between our paths to your format.

**Comment by herochen7372** [comment]
![image](https://github.com/wholebody3d/wholebody3d/assets/97960617/845f2666-67e9-4f15-ae7a-a817f0383d6a)
![image](https://github.com/wholebody3d/wholebody3d/assets/97960617/27c77eef-005b-4a94-9522-59a2ab145612)

you provide 15 actions in list, but there is act_16 in dataset.

**Comment by Zhuyue0324** [comment]
![Screenshot 2024-01-24 at 14-54-25 File Browser](https://github.com/wholebody3d/wholebody3d/assets/18241456/1f9fe6e3-e2f9-4c41-aced-ac1d8114e628)

**Comment by herochen7372** [comment]
Sorry，I mean this [https://github.com/IDEA-Research/OSX/issues/108](https://github.com/IDEA-Research/OSX/issues/108)

**Comment by Zhuyue0324** [comment]
This is the original site where I get the image data from. I don't know what is the act 16 (and 17 if there is one in your list)

**Comment by herochen7372** [comment]
Ok，thank you！

**Comment by Zhuyue0324** [comment]
In worst case, you can just ignore the act 16 and try matching annotations of the 15 actions we provide

**Comment by Zhuyue0324** [comment]
No, they are not continuous. First I only compile 1 from each 5 frames from video. Then during the quality assessment step we choose to form only 100k sample triplets out of all samples we compiled with the smallest errors according to our 4-corner error metric.

**Comment by herochen7372** [comment]
Ok，thank you！

**Comment by Zhuyue0324** [comment]
I first downloaded the video data from their original site http://vision.imar.ro/human3.6m/description.php
Then I use the code in [data_preparation.py](https://github.com/wholebody3d/wholebody3d/tree/main/datasets/data_preparation.py) to convert mp4 into images

**Comment by Z-mingyu** [comment]
> I first downloaded the video data from their original site http://vision.imar.ro/human3.6m/description.php Then I use the code in [data_preparation.py](https://github.com/wholebody3d/wholebody3d/tree/main/datasets/data_preparation.py) to convert mp4 into images

I found the frame_id in the  dataset, so I can get the image you selected
