### ISSUE TITLE
About the difference between two task

### ISSUE THREAD

**Issue by seekFire** [wholebody3d/wholebody3d#27]
Task "**2D → 3D**" is based on single frame input & single frame output
While task "**I2D → 3D**" is based on multi-frames(or frame sequence) input & single frame output.
Is it right?

**Comment by Zhuyue0324** [comment]
No. '2D' means  your input is 2D skeleton which all keypoints given.
'I' in 'I2D' means incomplete, so you still take 2D skeleton but with some of them missing (annotated as 0s, to simulate occluded points) and you need to predict complete 3D skeleton

**Comment by seekFire** [comment]
> No. '2D' means your input is 2D skeleton which all keypoints are given. 'I' in 'I2D' means incomplete, so you still take 2D skeleton but with some of them missing (annotated as 0s, to simulate occluded points) and you need to predict complete 3D skeleton

Wow, thank you for your reply! I think the model of task "**I2D → 3D**" is more practical!
