### ISSUE TITLE
Question about the task IMGTo3D

### ISSUE THREAD

**Issue by seekFire** [wholebody3d/wholebody3d#29]
In this task, should CPN(Cascade Pyramid Network) always supply complete 2D keypoints? When it should but can't work on some actions(for example, limb occlusion), can I use the model in the task **I2D -> 3D** as follow-up？
The second question is when keypoint is masked，will the value of it be filled with zero?

**Comment by Zhuyue0324** [comment]
For your first question, when we trained CPN+jointformer, we gave all keypoints intermediate 2D supervision, even it is occluded. But you can also do as what you have claimed: predicting 2D as well as a visibility or confidence value, and only pass the high confidence 2D prediction to an incomplete-2D-to-3D network.

For your second question, we filled the masked value with 0 as well as providing the confidence value.

**Comment by seekFire** [comment]
@Zhuyue0324 Thank you very much!
