### ISSUE TITLE
Are the models used for creating dataset more accurate than models metioned in benchmark.md?

### ISSUE THREAD

**Issue by seekFire** [wholebody3d/wholebody3d#30]
![2024-04-03 09-59-21 的屏幕截图](https://github.com/wholebody3d/wholebody3d/assets/26456083/cec23204-54bd-4491-a63c-51dcc9294772)

**Comment by seekFire** [comment]
Sorry, I noticed that the models used for creating dataset seems can not be used directly.

**Comment by Zhuyue0324** [comment]
No, those models used for creating dataset are not among benchmark models. Completion is Incomplete 3D->3D and Diffusion is image of hand/face+2D noise->2D, which are not fitting for the tasks directly.

**Comment by seekFire** [comment]
@Zhuyue0324 Thank you for your reply!
