### ISSUE TITLE
Issue about input of task (I)2D->3D

### ISSUE THREAD

**Issue by seekFire** [wholebody3d/wholebody3d#31]
![2024-04-07 16-25-42 的屏幕截图](https://github.com/wholebody3d/wholebody3d/assets/26456083/ae6ad79c-e094-4319-a63b-e661ba5ca899)
The annotation of 1st line indicates that the input of JointFormer should be in **meter**, so when I get 2D coordinates through the inference of 2D-HPE model, How to convert the 2D coordinates from **pixel** to **meter**?
Besides, when I get the final 3d output of JointFormer, how to restore it from **meter** to **pixel**? Is this the inverse process of above?

**Comment by Zhuyue0324** [comment]
You can just put 2D pixel number as input and predict 3D meter number. If you want 2D meter value, you can use camera intrinsic parameter.
Pixel unit is only use for 2D image in our project and never for 3D position. You don't need to transform 3D meter data into pixel.

**Comment by seekFire** [comment]
@Zhuyue0324 Thank you for your reply! So when JointFormer gets 2D pixel coordinates as input,

**Comment by seekFire** [comment]
@Zhuyue0324 Thank you for your reply! So when JointFormer gets 2D pixel coordinates as input, Do we need to do any preprocessing? Normailize or just do nothing but raw?

**Comment by Zhuyue0324** [comment]
You can do anyway you want. What I did is to divide the pixel number by 1000, because the image is about 1000x1000 so I 'normalize' the pixel data into between 0 and 1

**Comment by seekFire** [comment]
@Zhuyue0324 I got it! Thank you very much!
