### ISSUE TITLE
human36m&wholebody3d

### ISSUE THREAD

**Issue by herochen7372** [wholebody3d/wholebody3d#33]
I visualise looking at the 3d skeletal points of wholebody3d and human36m corresponding pictures, but they seem to be mirror symmetrical. Can you help me?

**Comment by Zhuyue0324** [comment]
If they are mirror symmetrical, there are two possibilities: either you use keypoints from one camera view with the image from opposite camera view, or you need to adjust the axis direction(likely the height), which direction is positive direction.

**Comment by herochen7372** [comment]
![1713619786257](https://github.com/wholebody3d/wholebody3d/assets/97960617/fcc16587-87af-4a6b-a0bd-31b3959d29d7)
ok，thanks.

**Comment by herochen7372** [comment]
Hi，i solve it. But i visualised the 3d skeletal points of wholebody3d vs human36m corresponding images and found them to be quite different. Specifically, the model that human36m did the training on will test much worse with wholebody3d than on human36m.
![image](https://github.com/wholebody3d/wholebody3d/assets/97960617/9a67d8a9-57fc-4d5b-a77b-eb3bac9439d5)

**Comment by Zhuyue0324** [comment]
wholebody3d use coco-wholebody skeleton, not exactly human3.6m ones

**Comment by herochen7372** [comment]
Thanks，i get it.
