### ISSUE TITLE
The coordinates of keypoints_3d

### ISSUE THREAD

**Issue by chenmingTHU** [wholebody3d/wholebody3d#5]
Thanks for your great work! I am trying to project the 3d keypoints provided in the RGBto3D_train.json with camera parameters provided in meta_data. Are the 3d keypoints in RGBto3D_train.json in camera coordinates or world coordinates ? Thank you.

**Comment by chenmingTHU** [comment]
> Thanks for your great work! I am trying to project the 3d keypoints provided in the RGBto3D_train.json with camera parameters provided in meta_data. Are the 3d keypoints in RGBto3D_train.json in camera coordinates or world coordinates ? Thank you.

Here is my code, and the projected 2d keypoints seems to be wrong.
![image](https://user-images.githubusercontent.com/22796506/209934199-f6b3af05-7172-4ea8-86d0-c9063406ac7d.png)
![image](https://user-images.githubusercontent.com/22796506/209934358-c2695b43-fc08-421a-95d3-2688719b9029.png)

**Comment by Zhuyue0324** [comment]
The 3d keypoints in RGBto3D_train.json are actually R_cam * X_global, so you don't need R_cam but you need T_cam to project correctly into 2D.
The 2d keypoints are K_cam(R_cam * X_global + T_cam) then X[:, :, :2] /= X[:, :, 2:3]

If you pay attention to the image paths, you will find that all 4k, 4k+1, 4k+2 and 4k+3 image samples are the same 3D sample but 4 different camera views. Our 3D annotations of them are the same except a different rotation is applied.

Also, if you want 2D annotations for image->2D->3D for RGBto3D task, actually the 2Dto3D_train.json and RGBto3D_train.json are aligned, so the k-th 2D annotation in 2Dto3D_train.json is also for k-th image in RGBto3D_train.json

Sorry for the confusion of coordinate system we used for our annotations.

**Comment by chenmingTHU** [comment]
> 

Thank you for your reply~

**Comment by herochen7372** [comment]
Hi, How can I project the 3d keypoints in RGBto3D_train.json to RGB image？Could you provide this code？

**Comment by herochen7372** [comment]
Ok，thank you, i try it.

**Comment by herochen7372** [comment]
> > Thanks for your great work! I am trying to project the 3d keypoints provided in the RGBto3D_train.json with camera parameters provided in meta_data. Are the 3d keypoints in RGBto3D_train.json in camera coordinates or world coordinates ? Thank you.感谢您的出色工作！我正在尝试使用 meta_data 中提供的相机参数投影RGBto3D_train.json中提供的 3d 关键点。3D关键点是相机坐标还是世界坐标RGBto3D_train.json？谢谢。
> 
> Here is my code, and the projected 2d keypoints seems to be wrong.这是我的代码，预计的 2d 关键点似乎是错误的。 ![image](https://user-images.githubusercontent.com/22796506/209934199-f6b3af05-7172-4ea8-86d0-c9063406ac7d.png) ![image](https://user-images.githubusercontent.com/22796506/209934358-c2695b43-fc08-421a-95d3-2688719b9029.png)

Hi，I try your code，and camera parameters（https://github.com/karfly/human36m-camera-parameters/tree/master），but get error 2d joints. Can you help me？
![image](https://github.com/wholebody3d/wholebody3d/assets/97960617/54b69c0b-4358-4c44-a017-f112f6eedc60)

**Comment by herochen7372** [comment]
> The 3d keypoints in RGBto3D_train.json are actually R_cam * X_global, so you don't need R_cam but you need T_cam to project correctly into 2D. The 2d keypoints are K_cam(R_cam * X_global + T_cam) then X[:, :, :2] /= X[:, :, 2:3]
> 
> So the code looks like:
> 
> ```
> X = torch.transpose(torch.matmul(R_cam, torch.transpose(X_data_3d, 1, 2)), 1, 2)+T_cam.unsqueeze(1)
> X = torch.transpose(torch.matmul(K_cam.unsqueeze(0), torch.transpose(X, 1, 2)), 1, 2)
> X[:, :, :2] /= X[:, :, 2:3]
> X_data_2d = X[:, :, :2]
> ```

Hi，I try it by this code with the camera parameters in your demo，but there is nothing in the image. Could you help?
![image](https://github.com/wholebody3d/wholebody3d/assets/97960617/3fdd1d1d-ea30-4332-a809-feb5797a7d15)
![image](https://github.com/wholebody3d/wholebody3d/assets/97960617/425576bc-0e45-4394-88de-cb932a7ad6c3)

**Comment by Zhuyue0324** [comment]
For getting camera parameters from metadata, i used the function adapted from https://github.com/karfly/human36m-camera-parameters 
```
def get_h36m_one_camera_parameters(metadata, camera, subject, factor=0.001):  # This is almost the get_camera_parameters function in their generate.py
    # some black magic with indexes
    metadata_slice = np.zeros(15)
    start = 6 * (camera * 11 + (subject - 1))

    metadata_slice[:6] = metadata[start:start + 6]
    metadata_slice[6:] = metadata[265 + camera * 9 - 1:265 + (camera + 1) * 9 - 1]

    # extrinsics
    x, y, z = -metadata_slice[0], metadata_slice[1], -metadata_slice[2]

    R_x = np.array([
        [1, 0, 0],
        [0, np.cos(x), np.sin(x)],
        [0, -np.sin(x), np.cos(x)]
    ])

    R_y = np.array([
        [np.cos(y), 0, np.sin(y)],
        [0, 1, 0],
        [-np.sin(y), 0, np.cos(y)]
    ])

    R_z = np.array([
        [np.cos(z), np.sin(z), 0],
        [-np.sin(z), np.cos(z), 0],
        [0, 0, 1]
    ])

    R = R_x @ R_y @ R_z

    t = metadata_slice[3:6].reshape(-1, 1)
    t = -R @ t

    R = R.tolist()
    t = t.tolist()
    R = torch.tensor(R)
    t = torch.transpose(torch.tensor(t), 0, 1)*factor

    # intrinsics
    fx, fy = metadata_slice[6:8]
    cx, cy = metadata_slice[8:10]
    calibration_matrix = torch.tensor([
        [fx*factor, 0.0, cx*factor],
        [0.0, fy*factor, cy*factor],
        [0.0, 0.0, 1.0]
    ], dtype=torch.float)

    k1, k2, k3 = metadata_slice[10:13]
    p1, p2 = metadata_slice[13:15]
    distortion = torch.tensor([k1, k2, p1, p2, k3], dtype=torch.float)

    return R, t, calibration_matrix, distortion


def get_h36m_parameter(metadata):   # This one I added to put all camera parameters in lists 
    K_list, R_list, T_list, distortion_list = [], [[],[],[],[]], [[],[],[],[]], []
    camera = [3,1,0,2]   # So as to put into ['60457274', '55011271', '54138969', '58860488'] order, which rotates starting from 'front' camera
    for i in range(4):
        for subject in [1,5,6,7,8,9,11]:
            R, T, K, distortion = get_h36m_one_camera_parameters(metadata, camera[i], subject)
            if subject == 1:
                K_list.append(K)
                distortion_list.append(distortion)
            R_list[i].append(R)
            T_list[i].append(T)
    return R_list, T_list, K_list, distortion_list
```

So you can check the following things:
1. Did you use the correct camera?
'''
X = torch.transpose(torch.matmul(R_cam, torch.transpose(X_data_3d, 1, 2)), 1, 2)+T_cam.unsqueeze(1)
X = torch.transpose(torch.matmul(K_cam.unsqueeze(0), torch.transpose(X, 1, 2)), 1, 2)
X[:, :, :2] /= X[:, :, 2:3]
X_data_2d = X[:, :, :2]
'''
This is the general 3D to 2D process. When computing 3D coordinates to 2D, I mentioned 'The 3d keypoints in RGBto3D_train.json are actually R_cam * X_global', so the R_cam in the previous function can be removed or replaced by identity matrix in this specific case.

**Comment by herochen7372** [comment]
Ok，thank you！
