### ISSUE TITLE
 Could you provide a script for projecting 3D keypoints from RGBto3D_train.json to 2D coordinate points of the image?

### ISSUE THREAD

**Issue by jiwei-dot** [wholebody3d/wholebody3d#6]
First of all, many thanks to the authors for providing such an important dataset.

But there are still questions about how to project the 3D keypoints in RGBto3D_train.json to the 2D coordinates of the image, and it's been confusing me all day.

Here is my code below:
![image](https://user-images.githubusercontent.com/74099954/217426029-70b999b6-5955-414f-93aa-a561fc755e8a.png)
（the extrinsics and intrinsics are obtained from https://github.com/karfly/human36m-camera-parameters/blob/master/camera-parameters.json）

But got the unexpected result below:
![image](https://user-images.githubusercontent.com/74099954/217426180-cc68cd9a-e5ba-4931-babf-4ee75752abde.png)

Looking forward to your reply!

**Comment by jiwei-dot** [comment]
Sorry for the wrong image name( it should be `S5_Directions_1.60457274_002190.jpg`).

After I change code like below:
![image](https://user-images.githubusercontent.com/74099954/217439305-80d2d754-ebc2-4c5f-85a9-91f103dc2eb1.png)

I get this result:
![image](https://user-images.githubusercontent.com/74099954/217439453-934e71f0-133c-4d04-ab13-4205bb87568c.png)

This seems to have the same problem as the last issue and is really bothering me too much.

**Comment by Zhuyue0324** [comment]
You can check the closed issue 5, who has the same problem as you do. I would say the answer is the same and I past here too.

The 3d keypoints in RGBto3D_train.json are actually R_cam * X_global, so you don't need R_cam but you need T_cam to project correctly into 2D.
The 2d keypoints are K_cam(R_cam * X_global + T_cam) then X[:, :, :2] /= X[:, :, 2:3]
So in your case, just change 
```
reproj = np.dot(R, keypoints_3d.T).T + t.T
```
to
```
reproj = keypoints_3d + t.T
```
and it should work.

If you pay attention to the image paths, you will find that all 4k, 4k+1, 4k+2 and 4k+3 image samples are the same 3D sample but 4 different camera views. Our 3D annotations of them are the same except a different rotation is applied.

Also, if you want 2D annotations for image->2D->3D for RGBto3D task, actually the 2Dto3D_train.json and RGBto3D_train.json are aligned, so the k-th 2D annotation in 2Dto3D_train.json is also for k-th image in RGBto3D_train.json

Sorry for the confusion of coordinate system we used for our annotations.

**Comment by jiwei-dot** [comment]
It works！！！
Since I'm just starting to study this field, I don't know enough about many simple things, and your advices really help me a lot.
Thanks again and wish you have a nice day✨✨✨
