### ISSUE TITLE
关于测试集

### ISSUE THREAD

**Issue by TDIT-haha** [wholebody3d/wholebody3d#7]
首先，非常感谢作者提供了如此重要的数据集。
我想获得RGBto3D_test_3d.json文件，请问能分享出来么？

**Comment by Zhuyue0324** [comment]
您好,
很遗憾我们现在不能分享RGBto3D_test_3d.json文件,因为我们正在计划组织一个leaderboard一样的平台,由用户上传在test数据上的预测结果后我们反馈误差分数,所以短期内我们将不会公开test数据集的groundtruth.
