### ISSUE TITLE
关于数据集名称

### ISSUE THREAD

**Issue by eric9687** [wholebody3d/wholebody3d#8]
你好，感谢你们提供了这么丰富的资源。

这个数据集的image_path就是"'S6/Images/Greeting 1.60457274/frame_1610.jpg'" 这样的。
S6是本来Human3.6M的subject循序，Greeting就是他们的action。
但是本来的Human3.6M有subaction，而在image_path没有subaction的标注。
还有image_path上的1.60457274指的是什么？

**Comment by Zhuyue0324** [comment]
你好
你的例子中, "Greeting 1"应该是它的action+subaction (例如Direction, Direction 1, Direction 2, ...这样)
60457274 是它的相机编号

**Comment by eric9687** [comment]
非常感谢您的回答。
按照你的说明， 我看了这些img_path的subaction。
但是，里面有没有数字的。比如，（“discussion" 和 “discussion 1”）， （“directions”， “directions 1”，“directions 2”）。
没有数字的action有特别的意思吗？

**Comment by Zhuyue0324** [comment]
并没有,没有数字的你可以理解为是" 0"
