### ISSUE TITLE
您好，请问在 2Dto3D_trian_part1.json 文件中读取得到的三维关键点如何和S1的某一帧动作进行匹配呢

### ISSUE THREAD

**Issue by Pangolin112** [wholebody3d/wholebody3d#9]

**Comment by Zhuyue0324** [comment]
您好

2Dto3D_train 是被用于进行lifting训练,使用2D点作为输入而不是用照片作为输入,所以我们没有直接给它的对应图片的路径

如果你使用 2Dto3D_train.json 而不是它的part文件,那么它和 RGBto3D_train.json 是按顺序一一对应的.

如果你使用part文件,由于part文件的按顺序合并就是总文件,所以第 2Dto3D_train_partX.json 的 第Y个数据对应 RGBto3D 中的第16000*(X-1)+Y个数据 (X=1,2...5)(Y=0...15999)

请注意,由于我们重新按 5-fold cross validation 进行分割成5个part, 所以每个part现在并不对应一个subject

**Comment by Zhuyue0324** [comment]
您好

如果你要多视角几何来计算,还是可以用2Dto3D的数据的, 具体请看 #6 , 简单来说是所有 4k, 4k+1, 4k+2 和 4k+3 的数据对应同一个 3D 位姿但是 4 个不同的相机方向, 不论是RGBto3D 还是 2Dto3D.

但由于整个数据集按照一个我们定义的误差度(在我们的paper中有解释)来排序3D位姿,所以所有样本顺序是被打乱的,没有连续的视频数据

**Comment by Pangolin112** [comment]
好的，非常感谢您的回复
